### PR TITLE
Updates css styles with bootstrapp css classes, so does not need to u…

### PR DESCRIPTION
**Pull request by cacods**
…se bootstrap css in the project

# Overview

Please replace this line with full information about your pull request. Make sure that tests pass before publishing it

---

Please preserve this line to notify @roll (lead of this repository)

### CODE REVIEW

**Comment by roll** [comment]
Hi @cacods,

It's a good idea. Is it possible to achieve?

**Comment by cacods** [comment]
I'm sorry @roll, I was trying to make a PR only for my fork but inadvertently I made it in the frictionless repository. That's because I closed it.

I did that because importing Bootstrap as a whole was interfering in the Dryad styles. So since there are few Bootstrap styles used in fricionless-components I tryed to extract only the ones actually used. I think I could did that but I'm not sure yet. Anyway I think it's necessary to organize better the CSS classes because I just pick that classes from the Bootstrap and added at the end of the report.css.

**Comment by roll** [comment]
@cacods 
No worries. If you manage to make it work can you please create a PR for `components` itself? This `bootstrap issue bothers me also - https://github.com/frictionlessdata/components/issues/5

**Comment by cacods** [comment]
It sounds good @roll. As soon as I have refactored the Bootstrap css classes I added, I make a new PR.

**Pull request closed without merging**
